name: gatsby deploy

on:
  push:
    # branches: main 브랜치에 push를 할 때마다 아래의 jobs를 실행
    branches: [main]

jobs:
  deploy:
    # name: 일련의 jobs flow를 정의하는데 해당 jobs의 이름을 deploy로 명명
    name: deploy
    # runs-on: 실행 환경을 ubuntu-latest로 설정
    runs-on: ubuntu-latest

    # steps: 일련의 실행 jobs를 아래에 기재. 위에서 아래로 actions가 실행
    steps:
      # name: 실행되는 job의 이름
      # uses: 이미 만들어진 액션을 사용
      # run: 실행시킬 명령어 (cmd)
      # env: 환경 변수
      - name: checkout code
        uses: actions/checkout@v2

      - name: packages install
        run: yarn install

      - name: gatsby build
        run: yarn build
        env:
          # API_KEY 에는 자신이 secret을 생성할 때 설정한 이름으로 넣어야 한다
          GH_API_KEY: ${{ secrets.API_KEY }}

      - name: deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # API_KEY 에는 자신이 secret을 생성할 때 설정한 이름으로 넣어야 한다
          GH_PAT: ${{ secrets.API_KEY }}
          BUILD_DIR: 'public/'
